//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HavaBusiness
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingPayment
    {
        public int Id { get; set; }
        public int BookingId { get; set; }
        public string CardHolderName { get; set; }
        public string ExpireDate { get; set; }
        public string CardNo { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CardType { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Common Common { get; set; }
    }
}
