//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HavaBusiness
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.BookingPayments = new HashSet<BookingPayment>();
            this.BookingProducts = new HashSet<BookingProduct>();
            this.BookingOptions = new HashSet<BookingOption>();
        }
    
        public int Id { get; set; }
        public Nullable<int> BookingTypeId { get; set; }
        public Nullable<System.DateTime> PickupDate { get; set; }
        public Nullable<System.TimeSpan> PickupTime { get; set; }
        public string PickupLocation { get; set; }
        public Nullable<System.TimeSpan> ReturnTime { get; set; }
        public string ReturnPickupLocation { get; set; }
        public string DropLocation { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public string RefNo { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> PartnerId { get; set; }
        public Nullable<int> NumberOfDays { get; set; }
        public Nullable<int> BookingStatusId { get; set; }
        public Nullable<int> TSPId { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
        public Nullable<int> PromotionId { get; set; }
        public Nullable<bool> HasPromotions { get; set; }
        public bool UserConfirmed { get; set; }
        public Nullable<int> UserId { get; set; }
        public bool IsReturn { get; set; }
        public Nullable<bool> IsAirportTransfer { get; set; }
    
        public virtual BookingStatu BookingStatu { get; set; }
        public virtual BookingType BookingType { get; set; }
        public virtual Partner Partner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingPayment> BookingPayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingProduct> BookingProducts { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Promotion Promotion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingOption> BookingOptions { get; set; }
    }
}
