//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HavaBusiness
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingProduct
    {
        public int Id { get; set; }
        public Nullable<int> BookingId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public bool IsAirPortTour { get; set; }
        public Nullable<int> AdditionalDays { get; set; }
        public Nullable<int> AdditionalHours { get; set; }
        public Nullable<int> AdditionalChufferDate { get; set; }
        public Nullable<int> AdditionalChufferHours { get; set; }
        public Nullable<int> NoOfChildSeats { get; set; }
        public Nullable<int> ChildSeatDays { get; set; }
    
        public virtual Booking Booking { get; set; }
    }
}
