//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HavaBusiness
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingOption
    {
        public int Id { get; set; }
        public int BookingId { get; set; }
        public string FlightNo { get; set; }
        public Nullable<int> FlyerProgramId { get; set; }
        public string FlyerReffNo { get; set; }
        public string PickupSign { get; set; }
        public string PickupSignReffNo { get; set; }
        public string NoteToDriver { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Booking Booking { get; set; }
    }
}
