//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HavaBusiness
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public int id { get; set; }
        public string country { get; set; }
        public string currency1 { get; set; }
        public string code { get; set; }
        public string symbol { get; set; }
    }
}
