//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HavaBusiness
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerPaymentRecord
    {
        public int Id { get; set; }
        public string PaymentStatus { get; set; }
        public string PaymentAmount { get; set; }
        public string PaymentCurrency { get; set; }
        public string PayerEmail { get; set; }
        public string ReceiverEmail { get; set; }
        public string TransactionID { get; set; }
        public Nullable<int> BookingId { get; set; }
        public string IPAddress { get; set; }
        public string DownloadStatus { get; set; }
        public Nullable<System.DateTime> CurrentDateTime { get; set; }
    }
}
