//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HavaBusiness
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuType
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string icon { get; set; }
    }
}
