//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HavaBusiness
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerCommission
    {
        public int Id { get; set; }
        public Nullable<int> PartnerId { get; set; }
        public Nullable<bool> IsMarkup { get; set; }
        public string percentage { get; set; }
        public Nullable<decimal> price { get; set; }
    
        public virtual Partner Partner { get; set; }
    }
}
