//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HavaBusiness
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerProductRate
    {
        public int Id { get; set; }
        public int PartnerId { get; set; }
        public int LocationId { get; set; }
        public int ProductId { get; set; }
        public Nullable<decimal> Rate { get; set; }
    
        public virtual LocationDetail LocationDetail { get; set; }
        public virtual Partner Partner { get; set; }
        public virtual Product Product { get; set; }
    }
}
