//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HavaBusiness
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerSite
    {
        public int PartnerId { get; set; }
        public int SiteId { get; set; }
    
        public virtual Partner Partner { get; set; }
        public virtual Partner Partner1 { get; set; }
        public virtual Site Site { get; set; }
    }
}
