//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HavaBusiness
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerProduct
    {
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> PartnerId { get; set; }
        public Nullable<decimal> HavaPrice { get; set; }
        public Nullable<decimal> MarketPrice { get; set; }
        public Nullable<decimal> PartnerSellingPrice { get; set; }
        public Nullable<bool> IsMarkUp { get; set; }
        public Nullable<decimal> Markup { get; set; }
        public Nullable<decimal> Percentage { get; set; }
    
        public virtual PartnerProduct PartnerProducts1 { get; set; }
        public virtual PartnerProduct PartnerProduct1 { get; set; }
        public virtual Partner Partner { get; set; }
    }
}
