//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HavaBusiness
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPVehicle
    {
        public int Id { get; set; }
        public bool IsAcive { get; set; }
        public string VehicleNo { get; set; }
        public string RegistrationNo { get; set; }
        public string DriverName { get; set; }
        public string DriverIdOrDLNo { get; set; }
        public Nullable<int> MaxPasengers { get; set; }
        public Nullable<int> MaxLuggages { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> TSPId { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual TSP TSP { get; set; }
        public virtual Product Product { get; set; }
    }
}
